version: "3.8"

services:
  sso_mongodb:
      image: mongo:5.0.13
      container_name: sso_mongodb_${SETUP_CUSTOMER}
      restart: always
      ports:
        - 17018:27017
      volumes:
        - ./mongoData:/data/db
        - ./DB_initial_data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}
        - MONGO_INITDB_DATABASE=admin
        - DATABASE
        - DB_USER
        - DB_PASS
        - DUMP_USER
        - DUMP_USER_PWD
        - SETUP_CUSTOMER

  sso_node_backend:
    image: layernextai/sso_node_backend:1.0.12
    container_name: sso_node_backend_${SETUP_CUSTOMER}
    restart: always
    ports:
      - "8889:8889"
    depends_on:
      - sso_mongodb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./sso-layerx-backend/logs:/usr/src/app/logs
      - ./sso-layerx-backend/storage:/usr/src/app/storage
    env_file:
      - ./.env

  sso_frontend:
    image: layernextai/sso_frontend_${SETUP_CUSTOMER}:1.0.12
    container_name: sso_frontend_${SETUP_CUSTOMER}
    restart: always
    ports:
      - "9097:9097"
    environment:
      - TZ:utc

  layerx_nginx:
    image: nginx
    container_name: layerx_nginx_${SETUP_CUSTOMER}
    volumes:
      - ./nginxData/nginx/templates:/etc/nginx/templates
      - ../dataset/layerx-sync-tool:/home/layerx-sync-tool
      - ./nginxData/certbot/conf:/etc/letsencrypt
      - ./nginxData/certbot/www:/var/www/certbot
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "82:80"
    environment:
      - NGINX_PORT=80
      - SSO_BACKEND_PORT=8889
      - SSO_FRONTEND_PORT=9097
      - DATALAKE_BACKEND_PORT=3001
      - DATALAKE_FRONTEND_PORT=9095
      - DATASET_BACKEND_PORT=4001
      - DATASET_FRONTEND_PORT=9098
      - STUDIO_BACKEND_PORT=9090
      - STUDIO_FRONTEND_PORT=9096
      - SETUP_CUSTOMER

project_name: myproject