#!/bin/bash

export $(grep -v '^#' .env | xargs -d '\n')
JWT_SECRET=$(openssl rand -hex 32)

# Generating random keys
DATALAKE_KEY=key_$(openssl rand -base64 60 | tr -dc 'a-z0-9' | head -c 32)
DATALAKE_SECRET=$(openssl rand -base64 45 | tr -dc 'a-z0-9' | head -c 20)
CHAT_KEY=key_$(openssl rand -base64 60 | tr -dc 'a-z0-9' | head -c 32)
CHAT_SECRET=$(openssl rand -base64 45 | tr -dc 'a-z0-9' | head -c 20)
GRAFANA_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-z0-9' | head -c 20)

# generate accounts env
accounts_env="./accounts/.env"
if [ -f $accounts_env ]; then
  echo "Existing env file found for accounts. replacing..."
  echo "Warning: If the system was already built, the system may become non functional due to regeneration of db passwords"
fi
cat > $accounts_env <<EOL
#DB
DB_HOST=sso_mongodb
DB_PORT=27017
DB_USER=sso_user
DB_PASS=$(openssl rand -hex 10)
DATABASE=authDB

#DUMP
DUMP_USER=layernext_dumprestoreuser
DUMP_USER_PWD=$(openssl rand -hex 10)
OUTPUT_DIRECTORY=accounts
#change dump keepeing days as prefer and use dump per day like 1,2,3,4,6,12,24
DUMP_KEEPING_DAYS=30
DUMP_PER_DAY=4

# Build time
SETUP_CUSTOMER=$SETUP_CUSTOMER
MONGODB_ADMIN_PASSWORD=$(openssl rand -hex 16)
SYNC_TOOL_PATH=./../dataset

#env
PORT=8888
TEAM_ID=$TEAM_ID

JWT_SECRET=$JWT_SECRET
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_FIRST_NAME=$ADMIN_FIRST_NAME
ADMIN_LAST_NAME=$ADMIN_LAST_NAME
ADMIN_PASSWORD=$ADMIN_PASSWORD_ENCRYPT

#apps
DATALAKE=2E7GG9DZB7J8G45
STUDIO=ZQ9YR6HDFGFRJKQ
SSO=1RMBHCWM8QIJ6QH
DATASET=8F7TT5VB77K0GGH

MAXIMUM_AVAILABLE_SEATS=2

BASE_URL=https://$ACCOUNTS_DOMAIN_URL
FRONT_END_BASE_URL=https://$ACCOUNTS_DOMAIN_URL
ANNO_INTERNAL_SERVER=http://host.docker.internal:8080

ENVIRONMENT=enterprise

#support email sendgrid
SUPPORT_EMAIL=$SUPPORT_EMAIL
SENDGRID_API_KEY=$SENDGRID_API_KEY
SES_AWS_REGION=$SES_AWS_REGION
SES_AWS_ACCESS_KEY_ID=$SES_AWS_ACCESS_KEY_ID
SES_AWS_SECRET_ACCESS_KEY=$SES_AWS_SECRET_ACCESS_KEY

# Google login
GOOGLE_API_KEY=$GOOGLE_API_KEY
GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
GOOGLE_REFRESH_TOKEN=$GOOGLE_REFRESH_TOKEN

#api key secrets
STUDIO_KEY=$STUDIO_KEY
STUDIO_SECRET=$STUDIO_SECRET
DATASET_KEY=$DATASET_KEY
DATASET_SECRET=$DATASET_KEY
ANALYTICS_KEY=$ANALYTICS_KEY
ANALYTICS_SECRET=$ANALYTICS_SECRET
DATALAKE_KEY=$DATALAKE_KEY
DATALAKE_SECRET=$DATALAKE_SECRET
CHAT_KEY=$CHAT_KEY
CHAT_SECRET=$CHAT_SECRET

LOG_BACKUP_COUNT=90

DOMAIN_URL=$DOMAIN_URL
INSTALLATION_UUID=$INSTALLATION_UUID
ONE_TIME_TOKEN=$ONE_TIME_TOKEN
CMS_TOKEN=$CMS_TOKEN
ACCOUNTS_DOMAIN_URL=$ACCOUNTS_DOMAIN_URL
CHAT_DOMAIN_URL=$CHAT_DOMAIN_URL
DATALAKE_DOMAIN_URL=$DATALAKE_DOMAIN_URL
API_DOMAIN_URL=$API_DOMAIN_URL

CMS_DOMAIN_URL=$CMS_DOMAIN_URL
EOL

# generate datalake env
datalake_env="./datalake/.env"
if [ -f $datalake_env ]; then
  echo "Existing env file found for datalake. replacing..."
  echo "Warning: If the system was already built, the system may become non functional due to regeneration of db passwords"
fi
cat > $datalake_env <<EOL
#DB
DB_HOST=datalake_mongodb
DB_PORT=27017
DB_USER=datalake_user
DB_PASS=$(openssl rand -hex 10)
DATABASE=datalakeDB

#DUMP
DUMP_USER=layernext_dumprestoreuser
DUMP_USER_PWD=$(openssl rand -hex 10)
OUTPUT_DIRECTORY=datalake
#change dump keepeing days as prefer and use dump per day like 1,2,3,4,6,12,24
DUMP_KEEPING_DAYS=30
DUMP_PER_DAY=4

# Build time
SETUP_CUSTOMER=$SETUP_CUSTOMER
MONGODB_ADMIN_PASSWORD=$(openssl rand -hex 16)

# Database
DB_CPU_LIMIT=$CPU_LIMIT
DB_MEMORY_LIMIT=$MEMORY_LIMIT

# Limits
CPU_LIMIT=$CPU_LIMIT
MEMORY_LIMIT=$MEMORY_LIMIT

NODE_CPU_LIMIT=$CPU_LIMIT
NODE_MEMORY_LIMIT=$MEMORY_LIMIT

FLASK_CPU_LIMIT=$CPU_LIMIT
FLASK_MEMORY_LIMIT=$MEMORY_LIMIT

#server
INSTANCE_TYPE=master

#env
PORT=3000
TEAM_ID=$TEAM_ID

JWT_SECRET=$JWT_SECRET

# Auth
SSO_INTERNAL_SERVER=http://sso_node_backend:8888

# storage
STORAGE_TYPE=$STORAGE_TYPE

#S3
AWS_ACCESS_KEY=$AWS_ACCESS_KEY
AWS_SECRET_KEY=$AWS_SECRET_KEY
AWS_REGION=$AWS_REGION
AWS_BUCKET_NAME=$AWS_BUCKET_NAME

#GCP
GCP_KEY_FILE_PATH=$GCP_KEY_FILE_PATH
GCP_PROJECT_ID=$GCP_PROJECT_ID

#AZURE
AZURE_ACCOUNT_NAME=$AZURE_ACCOUNT_NAME
AZURE_STORAGE_ACCOUNT_KEY=$AZURE_STORAGE_ACCOUNT_KEY

#LOCAL_STORAGE
LOCAL_STORAGE_PATH=$LOCAL_STORAGE_PATH

#BUCKETS
DEFAULT_BUCKET_NAME=$DEFAULT_BUCKET_NAME
ALL_BUCKETS=$ALL_BUCKETS

# Enabling optional features
SUBSEQUENT_CRAWL=$SUBSEQUENT_CRAWL

#CONNECTION DB
CONNECTION_DB_HOST=datalake_connection_mongodb
CONNECTION_DB_HOST_AIRBYTE=localhost
CONNECTION_DB_PORT=27017
CONNECTION_DB_USER=connection_user
CONNECTION_DB_PASS=$(openssl rand -hex 10)
CONNECTION_DATABASE=connectionDB
CONNECTION_DUMP_USER=connection_dumprestoreuser
CONNECTION_DUMP_USER_PWD=$(openssl rand -hex 10)
CONNECTION_MONGODB_ADMIN_PASSWORD=$(openssl rand -hex 16)
CONNECTION_MYSQL_DB_HOST_AIRBYTE=localhost
CONNECTION_MYSQL_DB_HOST=datalake_connection_mysql
CONNECTION_MYSQL_DB_PORT=3306
MYSQL_ROOT_PASSWORD=$(openssl rand -hex 16)
MYSQL_DATABASE=connectiondb
MYSQL_USER=connection_user
MYSQL_PASSWORD=$(openssl rand -hex 10)

AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT

LLM_API_PROVIDER_DOC_METADATA_GENERATION=openai
LLM_API_KEY_DOC_METADATA_GENERATION=$TENANT_OPENAI_API_KEY

LLM_API_PROVIDER_DOC_STRUCTURE_GENERATION=openai
LLM_API_KEY_DOC_STRUCTURE=$TENANT_OPENAI_API_KEY

LLM_API_PROVIDER_ELEM_SEARCH=openai
LLM_API_KEY_ELEM_SEARCH=$TENANT_OPENAI_API_KEY

LLM_API_PROVIDER_DATA_EXTRACTION=openai
LLM_API_KEY_DATA_EXTRACTION=$TENANT_OPENAI_API_KEY

LLM_API_PROVIDER_DATA_SOURCE_OVERVIEW_GENERATOR=openai
LLM_API_KEY_DATA_SOURCE_OVERVIEW_GENERATOR=$TENANT_OPENAI_API_KEY
LLM_MODEL_FIELD_DESCRIPTION_GENERATION=gpt-4o-mini
LLM_FIELD_DESCRIPTION_GENERATION_MAX_TOKEN_LIMIT=16000

LLM_DATA_SOURCE_OVERVIEW_GENERATION_MAX_TOKEN_LIMIT=32000
LLM_MODEL_DATA_SOURCE_OVERVIEW_GENERATION=gpt-4.1
MODEL_DATABASE_TRANSFORMATION=gpt-4o

MODEL_DOC_METADATA_GENERATION=gpt-4o-mini
MODEL_DOC_STRUCTURE_GENERATION=gpt-4o
MODEL_ELEM_SEARCH=gpt-4o
MODEL_DATA_EXTRACTION=gpt-4o

MODEL_ELEM_SEARCH=gpt-4o
MODEL_DATA_EXTRACTION=gpt-4o

LLM_API_PROVIDER_AUTO_TUNER=openai
MODEL_AUTO_TUNER=gpt-4o
LLM_API_KEY_AUTO_TUNER=$TENANT_OPENAI_API_KEY
MODEL_DATABASE_TRANSFORMATION=gpt-4o

LOAD_FROM_FILE=False

#Evaluation
LLM_API_PROVIDER_ANSWER_EVALUATION=openai
LLM_API_KEY_ANSWER_EVALUATION=$TENANT_OPENAI_API_KEY
MODEL_ANSWER_EVALUATION=gpt-4o

LLM_API_PROVIDER_KNOWLEDGE_PROCESS=openai
LLM_API_KEY_KNOWLEDGE_PROCESS=$TENANT_OPENAI_API_KEY
MODEL_KNOWLEDGE_PROCESS=gpt-4.1
LLM_KNOWLEDGE_PROCESS_MAX_TOKEN_LIMIT=4000

DATALAKE_KEY=$DATALAKE_KEY
DATALAKE_SECRET=$DATALAKE_SECRET

TEXT_SIMILARITY_THRESHOLD=0.75

PYTHON_BASE_URL=http://datalake_flask_backend:3100
API_URL=https://$API_DOMAIN_URL

LOCAL_STORAGE_PATH=$LOCAL_STORAGE_PATH
LOG_BACKUP_COUNT=90
DOMAIN_URL=$DOMAIN_URL
LLM_AGENT_INTERNAL_URL=http://llm_fast_api_backend:5082

LOAD_TABLES_LIST=

ENABLE_WINDOWS_AUTH=false
KERBEROS_USER=
KERBEROS_PASSWORD=

ADDITIONAL_SCHEMAS=
INSTALLATION_UUID=$INSTALLATION_UUID
TENANT_OPENAI_API_KEY=$TENANT_OPENAI_API_KEY
QB_AT=$QB_AT
QB_RT=$QB_RT
QB_REALM_ID=$QB_REALM_ID
ACCOUNTS_DOMAIN_URL=$ACCOUNTS_DOMAIN_URL
CHAT_DOMAIN_URL=$CHAT_DOMAIN_URL
DATALAKE_DOMAIN_URL=$DATALAKE_DOMAIN_URL
API_DOMAIN_URL=$API_DOMAIN_URL
ADMIN_FIRST_NAME=$ADMIN_FIRST_NAME
ADMIN_LAST_NAME=$ADMIN_LAST_NAME

CMS_TOKEN=$CMS_TOKEN

QB_CLIENT_ID=$QB_CLIENT_ID
QB_CLIENT_SECRET=$QB_CLIENT_SECRET
QB_REDIRECT_URI=$QB_REDIRECT_URI
QB_ENV=$QB_ENV
QB_SCOPES=$QB_SCOPES
CMS_DOMAIN_URL=$CMS_DOMAIN_URL

# Fivetran Keys
FIVETRAN_API_KEY=$FIVETRAN_API_KEY
FIVETRAN_API_SECRET=$FIVETRAN_API_SECRET
FIVETRAN_GROUP_ID=$FIVETRAN_GROUP_ID
EOL

# generate chat env
source_env="./chat/.env"
if [ -f $source_env ]; then
  echo "Existing env file found for chat. replacing..."
  echo "Warning: If the system was already built, the system may become non functional due to regeneration of db passwords"
fi
cat > $source_env <<EOL
#DB
DB_HOST=chat_mongodb
DB_PORT=27017
DB_USER=chat_user
DB_PASS=$(openssl rand -hex 10)
DATABASE=chatDB

#DUMP
DUMP_USER=layernext_dumprestoreuser
DUMP_USER_PWD=$(openssl rand -hex 10)

#change dump keepeing days as prefer and use dump per day like 1,2,3,4,6,12,24
DUMP_KEEPING_DAYS=30
DUMP_PER_DAY=4

TEAM_ID=$TEAM_ID

# Build time
SETUP_CUSTOMER=$SETUP_CUSTOMER
MONGODB_ADMIN_PASSWORD=$(openssl rand -hex 20)

DB_CPU_LIMIT=$CPU_LIMIT
DB_MEMORY_LIMIT=$MEMORY_LIMIT

JWT_SECRET = $JWT_SECRET

#LLM FAST-API
LLM_TYPE=openai

AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT
LLM_API_PROVIDER=openai
LLM_API_KEY=$AZURE_OPENAI_API_KEY
OPENAI_API_KEY=$TENANT_OPENAI_API_KEY
AZURE_OPENAI_API_VERSION=2024-08-01-preview
TEMPERATURE=0.7
IS_OPENAI_PRIORITY_ENABLED=True
CODE_REVIEW_OFF=True

MODEL=gpt-4.1
MODEL_SQL_GENERATION=gpt-4.1
MODEL_PYTHON_CODING=gpt-4.1
MODEL_DATA_LOCATE=gpt-4.1
MODEL_HYPOTHESIS=gpt-4o
MODEL_INSIGHT=gpt-4.1
MODEL_REPORT_GENERATOR=gpt-4.1
MODEL_JSON_OUTPUT=gpt-4.1
MODEL_DATA_REVIEWER=o3-mini
MODEL_DATA_GENERATOR=gpt-4.1
MODEL_UNSTRUCTURED_PROCESSING=o3-mini
MODEL_UNSTRUCTURED_LABEL_IDENTIFICATION=o3-mini
MODEL_VISUAL_REVIEWER=gpt-4o
CODE_REVIEW_MODEL=gpt-4.1
MODEL_DATA_REVIEWER=gpt-4.1
MODEL_VISUAL_RENDER=gpt-4.1
MODEL_COMPLEX_ANALYSIS=o3
MODEL_EXCEL_UPDATER=o3
MODEL_KNOWLEDGE_GENERATION=o3
MODEL_TX_ANALYZER=o3
MODEL_DOCUMENT_DATA_QUERY=o3

URL=http://datalake_node_backend:3000

# Auth
SSO_INTERNAL_SERVER=http://sso_node_backend:8888

APP_PORT=5082
DEBUG=False
COUNT_TOKENS=True

COMPANY=$SETUP_CUSTOMER

#limitation
FAST_CPU_LIMIT=2
FAST_MEMORY_LIMIT=2GB

#Sendgrid credentails
SUPPORT_EMAIL=$SUPPORT_EMAIL
SENDGRID_API_KEY=$SENDGRID_API_KEY
SES_AWS_REGION=$SES_AWS_REGION
SES_AWS_ACCESS_KEY_ID=$SES_AWS_ACCESS_KEY_ID
SES_AWS_SECRET_ACCESS_KEY=$SES_AWS_SECRET_ACCESS_KEY

FRONTEND_URL=https://$CHAT_DOMAIN_URL
METALAKE_URL=https://$DATALAKE_DOMAIN_URL

#api key secrets
API_KEY=$CHAT_KEY
SECRET_KEY=$CHAT_SECRET
LOG_BACKUP_COUNT=90
DOMAIN_URL=$DOMAIN_URL

CLIENT_EMAILS=


SIMULTANEOUS_INSIGHT_INVOKES_LIMIT=2
INSIGHT_PARALLEL_THREAD_COUNT=5
DAILY_TRIGGER_HOUR=04 
DAILY_TRIGGER_MINUTE=10 
TIME_ZONE=America/Winnipeg

INSTALLATION_UUID=$INSTALLATION_UUID
ACCOUNTS_DOMAIN_URL=$ACCOUNTS_DOMAIN_URL
CHAT_DOMAIN_URL=$CHAT_DOMAIN_URL
DATALAKE_DOMAIN_URL=$DATALAKE_DOMAIN_URL
API_DOMAIN_URL=$API_DOMAIN_URL
CMS_DOMAIN_URL=$CMS_DOMAIN_URL
CMS_TOKEN=$CMS_TOKEN
ADMIN_FIRST_NAME=$ADMIN_FIRST_NAME
ADMIN_LAST_NAME=$ADMIN_LAST_NAME
EOL

# generate ssl creator nginx env
ssl_nginx_env="./accounts/nginxData/.env"
if [ -f $ssl_nginx_env ]; then
  echo "Existing env file found for ssl nginx. replacing..."
fi
cat > $ssl_nginx_env <<EOL
# Build time
SETUP_CUSTOMER=$SETUP_CUSTOMER
DOMAIN_URL=$DOMAIN_URL
ACCOUNTS_DOMAIN_URL=$ACCOUNTS_DOMAIN_URL
CHAT_DOMAIN_URL=$CHAT_DOMAIN_URL
DATALAKE_DOMAIN_URL=$DATALAKE_DOMAIN_URL
API_DOMAIN_URL=$API_DOMAIN_URL
CMS_DOMAIN_URL=$CMS_DOMAIN_URL
EOL


# generate monitoring env
monitoring_env="./monitoring/.env"
if [ -f $monitoring_env ]; then
  echo "Existing env file found for monitoring. replacing..."
  echo "Warning: If the system was already built, the system may become non functional due to regeneration of db passwords"
fi
cat > $monitoring_env <<EOL
GRAFANA_USERNAME=$GRAFANA_USERNAME
GRAFANA_PASSWORD=$GRAFANA_PASSWORD
SMTP_SMARTHOST='smtp.sendgrid.net:587'
SMTP_FROM=$SMTP_FROM
SMTP_AUTH_USERNAME='apiKey'
SMTP_AUTH_PASSWORD=$SENDGRID_API_KEY
SUPPORT_EMAIL=$ALERT_SUPPORT_MAIL
SETUP_CUSTOMER=$SETUP_CUSTOMER
EOL

# generate central accounts env
central_accounts_env="./central-accounts/.env"
if [ -f $central_accounts_env ]; then
  echo "Existing env file found for accounts. replacing..."
  echo "Warning: If the system was already built, the system may become non functional due to regeneration of db passwords"
fi
cat > $central_accounts_env <<EOL
#DB
DB_HOST=central_sso_mongodb
DB_PORT=27017
DB_USER=central_sso_user
DB_PASS=$(openssl rand -hex 10)
DATABASE=authDB

#DUMP
DUMP_USER=layernext_dumprestoreuser
DUMP_USER_PWD=$(openssl rand -hex 10)
OUTPUT_DIRECTORY=central-accounts
#change dump keepeing days as prefer and use dump per day like 1,2,3,4,6,12,24
DUMP_KEEPING_DAYS=30
DUMP_PER_DAY=4

# Build time
SETUP_CUSTOMER=$SETUP_CUSTOMER
MONGODB_ADMIN_PASSWORD=$(openssl rand -hex 16)
SYNC_TOOL_PATH=./../dataset

#env
PORT=8888
TEAM_ID=$TEAM_ID

JWT_SECRET=$JWT_SECRET
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_FIRST_NAME=$ADMIN_FIRST_NAME
ADMIN_LAST_NAME=$ADMIN_LAST_NAME
ADMIN_PASSWORD=$ADMIN_PASSWORD_ENCRYPT

#apps
DATALAKE=2E7GG9DZB7J8G45
STUDIO=ZQ9YR6HDFGFRJKQ
SSO=1RMBHCWM8QIJ6QH
DATASET=8F7TT5VB77K0GGH

MAXIMUM_AVAILABLE_SEATS=2

BASE_URL=https://$ACCOUNTS_DOMAIN_URL
FRONT_END_BASE_URL=https://$ACCOUNTS_DOMAIN_URL
ANNO_INTERNAL_SERVER=http://host.docker.internal:8080

ENVIRONMENT=enterprise

#support email sendgrid
SUPPORT_EMAIL=$SUPPORT_EMAIL
SENDGRID_API_KEY=$SENDGRID_API_KEY
SES_AWS_REGION=$SES_AWS_REGION
SES_AWS_ACCESS_KEY_ID=$SES_AWS_ACCESS_KEY_ID
SES_AWS_SECRET_ACCESS_KEY=$SES_AWS_SECRET_ACCESS_KEY

# Google login
GOOGLE_API_KEY=$GOOGLE_API_KEY
GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
GOOGLE_REFRESH_TOKEN=$GOOGLE_REFRESH_TOKEN

#api key secrets
STUDIO_KEY=$STUDIO_KEY
STUDIO_SECRET=$STUDIO_SECRET
DATASET_KEY=$DATASET_KEY
DATASET_SECRET=$DATASET_KEY
ANALYTICS_KEY=$ANALYTICS_KEY
ANALYTICS_SECRET=$ANALYTICS_SECRET
DATALAKE_KEY=$DATALAKE_KEY
DATALAKE_SECRET=$DATALAKE_SECRET
CHAT_KEY=$CHAT_KEY
CHAT_SECRET=$CHAT_SECRET

LOG_BACKUP_COUNT=90

DOMAIN_URL=$DOMAIN_URL
INSTALLATION_UUID=$INSTALLATION_UUID
ONE_TIME_TOKEN=$ONE_TIME_TOKEN
CMS_TOKEN=$CMS_TOKEN
ACCOUNTS_DOMAIN_URL=$ACCOUNTS_DOMAIN_URL
CHAT_DOMAIN_URL=$CHAT_DOMAIN_URL
DATALAKE_DOMAIN_URL=$DATALAKE_DOMAIN_URL
API_DOMAIN_URL=$API_DOMAIN_URL

CMS_DOMAIN_URL=$CMS_DOMAIN_URL

#central-sso
NODE_ENV=production
JWT_ALG=RS256
JWT_ISSUER=https://sso.layernext.ai
JWT_AUDIENCE=layernext-services
JWT_KID=QLisK1EGON4NLVb9A-0uvA
JWT_PRIVATE_KEY_PATH=/secrets/jwt_private.pem
JWT_PUBLIC_KEY_PATH=/secrets/jwt_public.pem
SESSION_TOKEN_EXPIRES_IN=3600
REFRESH_TOKEN_EXPIRES_IN=604800
ONBOARDING_GRANT_TTL_SECONDS=900
ONE_TIME_TOKEN_EXPIRES=3
EOL