version: "3.8"
services:
  chat_mongodb:
    image: mongo:5.0.13
    restart: always
    ports:
      - 61017:27017
    volumes:
      - ./mongoData:/data/db
      - ./DB_initial_data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}
      - MONGO_INITDB_DATABASE=admin
      - DATABASE
      - DB_USER
      - DB_PASS
      - DUMP_USER
      - DUMP_USER_PWD
      - SETUP_CUSTOMER
      - TEAM_ID
    deploy:
      resources:
        limits:
          cpus: ${DB_CPU_LIMIT}
          memory: ${DB_MEMORY_LIMIT}

  chat_frontend:
    image: layernextai/chat_frontend:3.0.0
    restart: always
    ports:
      - "8099:8099"
    environment:
      - TZ:utc
      - LAYERNEXT_SUB_DOMAIN=${SETUP_CUSTOMER}
