version: "3.8"
services:
  chat_mongodb:
    image: mongo:5.0.13
    restart: always
    ports:
      - 61017:27017
    volumes:
      - ./mongoData:/data/db
      - ./DB_initial_data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      layernext_network:
        ipv4_address: 172.23.30.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}
      - MONGO_INITDB_DATABASE=admin
      - DATABASE
      - DB_USER
      - DB_PASS
      - DUMP_USER
      - DUMP_USER_PWD
      - SETUP_CUSTOMER
      - TEAM_ID
    deploy:
      resources:
        limits:
          cpus: ${DB_CPU_LIMIT}
          memory: ${DB_MEMORY_LIMIT}

  chat_frontend:
    image: layernextai/chat_frontend:3.7.0
    restart: always
    networks:
      layernext_network:
        ipv4_address: 172.23.30.3
    ports:
      - "8099:8099"
    environment:
      - TZ:utc
      - LAYERNEXT_SUB_DOMAIN=${SETUP_CUSTOMER}

  llm_fast_api_backend:
    image: layernextai/llm_fast_api_backend:3.8.1
    restart: always
    networks:
      layernext_network:
        ipv4_address: 172.23.30.4
    ports:
      - "5082:5082"
    volumes:
      - ./LLM-integration/logs:/app/logs
      - ./LLM-integration/images:/app/images
      - ./LLM-integration/media:/app/media
      - ./LLM-integration/files:/app/files
      - ./LLM-integration/storage/files:/app/storage/files
      - ./LLM-integration/storage/public:/app/storage/public
      - ./LLM-integration/memory_dumps:/app/memory_dumps
    depends_on:
      - chat_mongodb
    deploy:
      resources:
        limits:
          cpus: ${FAST_CPU_LIMIT}
          memory: ${FAST_MEMORY_LIMIT}
    env_file:
      - ./.env

networks:
  layernext_network:
    external: true
    ipam:
      config:
        - subnet: 172.23.0.0/16