global:
  # Sendgrid SMTP properties.
  smtp_smarthost: '${SMTP_SMARTHOST}'
  smtp_from: '${SMTP_FROM}'
  smtp_auth_username: '${SMTP_AUTH_USERNAME}'
  smtp_auth_password: '${SMTP_AUTH_PASSWORD}'

receivers:
  - name: mail
    email_configs:
    - to: "${SUPPORT_EMAIL}"
      headers:
        subject: "Alert on ${SETUP_CUSTOMER} ({{ .Status }}): {{ .CommonLabels.severity }} {{ .CommonAnnotations.message }} ({{ .CommonLabels.alertname }})"
      html: |
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Alert Notification</title>
              <style>
                body {
                  font-family: Arial, sans-serif;
                  color: #333;
                  background-color: #f4f4f4;
                  margin: 0;
                  padding: 20px;
                }
                .container {
                  max-width: 600px;
                  margin: auto;
                  background-color: #ffffff;
                  border: 1px solid #dddddd;
                  border-radius: 8px;
                  padding: 20px;
                }
                h1 {
                  color: #333;
                  font-size: 26px;
                  margin-bottom: 10px;
                  font-weight: bold;
                  border-bottom: 2px solid #4CAF50;
                  padding-bottom: 10px;
                }
                h2 {
                  color: #555;
                  font-size: 20px;
                  margin-bottom: 5px;
                  font-weight: bold;
                }
                ul {
                  list-style-type: none;
                  padding: 0;
                }
                li {
                  margin: 8px 0;
                }
                .label {
                  color: #007BFF;
                  font-weight: bold;
                }
                .annotation {
                  color: #FFC107;
                  font-style: italic;
                }
                .footer {
                  margin-top: 20px;
                  font-size: 12px;
                  color: #777;
                  text-align: center;
                }
                .alert-item {
                  border-bottom: 1px solid #dddddd;
                  padding-bottom: 10px;
                  margin-bottom: 10px;
                }
                .alert-item:last-child {
                  border-bottom: none;
                }
              </style>
            </head>
            <body>
              <div class="container">
                <h1>Alert Notification</h1>
                <p>
                  Hello,
                  <br><br>
                  You have the following active alerts:
                </p>
                <ul>
                  {{ range .Alerts }}
                  <li class="alert-item">
                    <h2>{{ .Labels.alertname }} on {{ .Labels.instance }}</h2>
                    <p><span class="label">Labels:</span></p>
                    <ul>
                      {{ range .Labels.SortedPairs }}
                      <li>- {{ .Name }}: {{ .Value }}</li>
                      {{ end }}
                    </ul>
                    <p><span class="annotation">Annotations:</span></p>
                    <ul>
                      {{ range .Annotations.SortedPairs }}
                      <li>- {{ .Name }}: {{ .Value }}</li>
                      {{ end }}
                    </ul>
                  </li>
                  {{ end }}
                </ul>
                <p class="footer">
                  This is an automated alert message. Please do not reply to this email.
                </p>
              </div>
            </body>
            </html>


route:
  group_wait: 100s  # Time to wait before sending the first notification about a new group of alerts.
  group_interval: 24h  # Minimum time to wait before sending a new notification about the same group of alerts.
  receiver: mail  # Default receiver for notifications.
  repeat_interval: 10s  # Default repeat interval for alerts not matched by specific routes.
  routes:
    - match:
        severity: critical
      repeat_interval: 1m  
    - match:
        severity: high
      repeat_interval: 1m  
    - match:
        severity: medium
      repeat_interval: 5m 
    - match:
        severity: low
      repeat_interval: 15m  
