version: "3.8"
services:
  dataset_mongodb:
      image: mongo:5.0.13
      restart: always
      ports:
        - 47017:27017
      volumes:
        - ./mongoData:/data/db
        - ./DB_initial_data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}
        - MONGO_INITDB_DATABASE=admin
        - DATABASE
        - DB_USER
        - DB_PASS
        - DUMP_USER
        - DUMP_USER_PWD
        - SETUP_CUSTOMER

  dataset_node_backend:
    image: layernextai/dataset_node_backend:1.0.17.2
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - dataset_mongodb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./dataset-manager-nodejs/logs:/usr/src/app/dataset-manager-nodejs/logs
      - ./dataset-manager-python-processor/logs:/usr/src/app/dataset-manager-python-processor/logs
      - ./dataset-manager-nodejs/storage:/usr/src/app/dataset-manager-nodejs/storage
    env_file:
      - ./.env

  dataset_frontend:
    image: layernextai/dataset_frontend:1.0.17.2
    restart: always
    ports:
      - "8098:8098"
    environment:
      - TZ:utc
      - LAYERNEXT_SUB_DOMAIN=${SETUP_CUSTOMER}