version: '3.8'

services:
  node_exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node_exporter
    ports:
      - "9100:9100" # Expose 9100
    restart: always
    networks:
      - layernext_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    ports:
      - "9101:8080" # Expose 9101
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    networks:
      - layernext_network

  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
      - node_exporter
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      - layernext_network

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - 9102:3000
    volumes:
      - ./grafana-provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana-provisioning/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana-provisioning/dashboards/container_monitoring_dashboard.json:/var/lib/grafana/dashboards/container_monitoring_dashboard.json
      - ./grafana-provisioning/dashboards/server_monitoring_dashboard.json:/var/lib/grafana/dashboards/server_monitoring_dashboard.json
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_PROVISIONING_PATH=/etc/grafana/provisioning
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - layernext_network

  alertmanager:
    image: prom/alertmanager:v0.27.0
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    environment:
      - SMTP_SMARTHOST=${SMTP_SMARTHOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_AUTH_USERNAME=${SMTP_AUTH_USERNAME}
      - SMTP_AUTH_PASSWORD=${SMTP_AUTH_PASSWORD}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
    ports:
      - "9103:9093"
    volumes:
      - ./alertmanager/alertmanager-entrypoint.sh:/usr/local/bin/alertmanager-entrypoint.sh
      - "./alertmanager:/config"
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/data
    restart: always
    entrypoint: [ "/usr/local/bin/alertmanager-entrypoint.sh" ]
    depends_on:
      - grafana
    networks:
      - layernext_network

volumes:
  prometheus-data:
  grafana_data:
  alertmanager_data:


networks:
  layernext_network:
    external: true
