version: "3.8"
services:
  datalake_mongodb:
      image: mongo:5.0.13
      restart: always
      ports:
        - 37017:27017
      volumes:
        - ./mongoData:/data/db
        - ./DB_initial_data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}
        - MONGO_INITDB_DATABASE=${DATABASE}
        - DB_USER
        - DB_PASS
        - AWS_BUCKET_NAME
        - SETUP_CUSTOMER
      deploy:
        resources:
            limits:
              cpus: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}

  datalake_node_backend:
    image: layernextai/datalake_node_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - datalake_mongodb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./datalake-nodejs/logs:/usr/src/app/datalake-nodejs/logs
      - ./datalake-nodejs/storage:/usr/src/app/datalake-nodejs/storage
    env_file:
      - ./.env

  datalake_frontend:
    image: layernextai/datalake_frontend_${SETUP_CUSTOMER}
    restart: always
    ports:
      - "8095:8095"
    environment:
      - TZ:utc