version: "3.8"

services:
  datalake_mongodb:
      image: mongo:5.0.13
      container_name: datalake_mongodb_${SETUP_CUSTOMER}
      restart: always
      ports:
        - 37018:27017
      volumes:
        - ./mongoData:/data/db
        - ./DB_initial_data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}
        - MONGO_INITDB_DATABASE=admin
        - DATABASE
        - DB_USER
        - DB_PASS
        - DUMP_USER
        - DUMP_USER_PWD
        - AWS_BUCKET_NAME
        - SETUP_CUSTOMER
      deploy:
        resources:
            limits:
              cpus: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}

  datalake_node_backend:
    image: layernextai/datalake_node_backend:1.0.12
    container_name: datalake_node_backend_${SETUP_CUSTOMER}
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - datalake_mongodb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./datalake-nodejs/logs:/usr/src/app/datalake-nodejs/logs
      - ./datalake-nodejs/storage:/usr/src/app/datalake-nodejs/storage
    env_file:
      - ./.env

  datalake_frontend:
    image: layernextai/datalake_frontend_${SETUP_CUSTOMER}:1.0.12
    container_name: datalake_frontend_${SETUP_CUSTOMER}
    restart: always
    ports:
      - "9095:9095"
    environment:
      - TZ:utc

x-compose-project-name: my-project